In [1]:
import polars as pl
import pandas as pd

In [2]:
file_path = 'C:/Users/APIN PC/OneDrive/Documents/DS/DE_Inter/aws_project/data/Pakistan Largest Ecommerce Dataset.csv'

cols = ['item_id', 'status', 'created_at', 'sku', 
        'price', 'qty_ordered', 'grand_total', 'increment_id', 
        'category_name_1', 'sales_commission_code', 'discount_amount',
        'payment_method', 'Working Date', 'BI Status', ' MV ', 'Year',
        'Month', 'Customer Since', 'M-Y', 'FY', 'Customer ID']

In [3]:
df_pd = pd.read_csv(file_path, usecols=cols)
df_pl = pl.read_csv(file_path, columns=cols, low_memory=True, ignore_errors=True)

C:\Users\APIN-PC\AppData\Local\Temp\ipykernel_15268\2096382363.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df_pd = pd.read_csv(file_path, usecols=cols)

In [4]:
def datatypes_comparison():
    # Converting polars read to series
    b = df_pl.dtypes
    pl_series = pd.Series(b)

    # Converting pandas csv read to series and stripping irrelevant data.
    a = df_pd.dtypes
    pd_series = pd.Series(a)
    pl_cols_list = []
    for row in pd_series:
        row.str.strip(' ')
        pl_cols_list.append(str(row))
    pd_series_final = pd.Series(pl_cols_list)

    # Converting columns names to series.
    cols = df_pd.columns
    cols_fin = pd.Series(cols)

    # Concating all series to a dataframe.
    fin_df = pd.concat([cols_fin, pd_series_final, pl_series], axis=1)
    return fin_df

In [ ]:
dtypes_df = datatypes_comparison()

dtypes_df = dtypes_df.rename(columns = {0:'Columns', 1:'Pandas_dtype', 2:'Polars_dtype'})
dtypes_df

In [18]:
df_pd.head(3)

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,sales_commission_code,...,payment_method,Working Date,BI Status,MV,Year,Month,Customer Since,M-Y,FY,Customer ID
0,211131,complete,07/01/2016,kreations_YI 06-L,1950.0,1,1950.0,100147443,Women's Fashion,\N,...,cod,07/01/2016,#REF!,"1,950",2016,7,2016-7,Jul-16,FY17,1.0
1,211133,canceled,07/01/2016,kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Bo...,240.0,1,240.0,100147444,Beauty & Grooming,\N,...,cod,07/01/2016,Gross,240,2016,7,2016-7,Jul-16,FY17,2.0
2,211134,canceled,07/01/2016,Ego_UP0017-999-MR0,2450.0,1,2450.0,100147445,Women's Fashion,\N,...,cod,07/01/2016,Gross,"2,450",2016,7,2016-7,Jul-16,FY17,3.0

In [4]:
df_pd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 584524 entries, 0 to 584523
Data columns (total 21 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   item_id                584524 non-null  int64
 1   status                 584509 non-null  object
 2   created_at             584524 non-null  object
 3   sku                    584504 non-null  object
 4   price                  584524 non-null  float64
 5   qty_ordered            584524 non-null  int64
 6   grand_total            584524 non-null  float64
 7   increment_id           584524 non-null  object
 8   category_name_1        584360 non-null  object
 9   sales_commission_code  447346 non-null  object
 10  discount_amount        584524 non-null  float64
 11  payment_method         584524 non-null  object
 12  Working Date           584524 non-null  object
 13  BI Status              584524 non-null  object
 14   MV                    584524 non-null  object
 15  Year                   584524 non-null  int64
 16  Month                  584524 non-null  int64
 17  Customer Since         584513 non-null  object
 18  M-Y                    584524 non-null  object
 19  FY                     584524 non-null  object
 20  Customer ID            584513 non-null  float64
dtypes: float64(4), int64(4), object(13)
memory usage: 93.7+ MB

### FUNCTIONS

In [4]:
def df_cleaning(partition_df):
    """
    This function drops irrelevant columns and selected 
    rows from the partitions.
    Args:
        partition_df (_type_): _description_
    """
    col_to_drop = ['sales_commission_code', 'Working Date', 'M-Y']
    for cols in col_to_drop:
        if cols in partition_df.columns:
            partition_df = partition_df.drop(columns=cols)
        else:
            pass

    vals_dropped_df = partition_df.dropna()

    vals_dropped_df = vals_dropped_df[~(vals_dropped_df['category_name_1'] == r'\N')]
    vals_dropped_df = vals_dropped_df[~(vals_dropped_df['status'] == r'\N')]
    vals_dropped_df = vals_dropped_df[~(vals_dropped_df['BI Status'] == r'#REF!')]
    # vals_dropped_df = vals_dropped_df.reset_index()
    vals_dropped_df.reset_index(inplace=True)

    return vals_dropped_df



def df_transforming(data):
    """
    This function transforms the data
    Args:
        data (pd.DataFrame): Cleaned Dataframe

    Returns:
        pd.DataFrame: Transformed Data
    """
    data[' MV ' ] = (data[' MV '].replace(r',', '', regex=True))
    data[' MV ' ] = (data[' MV '].replace(r'-', 0, regex=True))
    data['Customer ID'] = data['Customer ID'].astype(int)
    data[' MV ' ] = pd.to_numeric(data[' MV '])#, errors='coerce')
    month_map = {1: 'January', 2: 'February', 3: 'March',
                4: 'April', 5: 'May', 6: 'June', 7: 'July',
                8: 'August', 9: 'September', 10: 'October', 
                11: 'November', 12: 'December'}
    data['Month'] = data['Month'].map(month_map)

    data = data.rename(columns={'sku': 'stock_keeping_unit', 'category_name_1': 'category_name',
                        ' MV ': 'market_value', 'BI Status': 'BI_status',
                        'Customer Since': 'customer_since', 'Customer ID': 'customer_id'})
    data = data.drop(columns='index')
    return data

In [5]:
clean_df = df_cleaning(df_pd)
trans_df = df_transforming(clean_df)

trans_df.info()
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 576480 entries, 0 to 576479
Data columns (total 18 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   item_id             576480 non-null  int64
 1   status              576480 non-null  object
 2   created_at          576480 non-null  object
 3   stock_keeping_unit  576480 non-null  object
 4   price               576480 non-null  float64
 5   qty_ordered         576480 non-null  int64
 6   grand_total         576480 non-null  float64
 7   increment_id        576480 non-null  object
 8   category_name       576480 non-null  object
 9   discount_amount     576480 non-null  float64
 10  payment_method      576480 non-null  object
 11  BI_status           576480 non-null  object
 12  market_value        576480 non-null  int64
 13  Year                576480 non-null  int64
 14  Month               576480 non-null  object
 15  customer_since      576480 non-null  object
 16  FY                  576480 non-null  object
 17  customer_id         576480 non-null  int64
dtypes: float64(3), int64(5), object(10)
memory usage: 79.2+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 576480 entries, 0 to 576479
Data columns (total 19 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   index            576480 non-null  int64
 1   item_id          576480 non-null  int64
 2   status           576480 non-null  object
 3   created_at       576480 non-null  object
 4   sku              576480 non-null  object
 5   price            576480 non-null  float64
 6   qty_ordered      576480 non-null  int64
 7   grand_total      576480 non-null  float64
 8   increment_id     576480 non-null  object
 9   category_name_1  576480 non-null  object
 10  discount_amount  576480 non-null  float64
 11  payment_method   576480 non-null  object
 12  BI Status        576480 non-null  object
 13   MV              576480 non-null  int64
 14  Year             576480 non-null  int64
 15  Month            576480 non-null  object
 16  Customer Since   576480 non-null  object
 17  FY               576480 non-null  object
 18  Customer ID      576480 non-null  int64
dtypes: float64(3), int64(6), object(10)
memory usage: 83.6+ MB

In [25]:
import numpy as np

"237983"

pd.set_option('display.max_rows', None)
# for row in trans_df[trans_df.market_value.isna()]:
#     if row == np.True_:
#         print(row.index)

ab = trans_df[trans_df.market_value.isna() == np.True_]
ac = ab.index

ad = ac.tolist()
print(len(ad))


trans_df.iloc[ad]

df_pd[df_pd['item_id'] == 218538]

2203

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,sales_commission_code,...,payment_method,Working Date,BI Status,MV,Year,Month,Customer Since,M-Y,FY,Customer ID
6598,218538,canceled,7/26/2016,"west point_Deluxe Juicer, Blender & Grinder - ...",0.0,1,0.0,100152813,Appliances,\N,...,cod,7/26/2016,Gross,-,2016,7,2016-7,Jul-16,FY17,1961.0

Convert 
- MV columns to float
- Month integer to String and name of month in reality.
- Customer Id to Integer


Drop 
- Working Date and created_at are the same thing. 
- Customer_since and M-Y are the same thing
    + Drop Working date, M-Y

In [30]:
clean_df[ab]

ValueError: Boolean array expected for the condition, not object

In [ ]:
# # ad = clean_df['Working Date'] == clean_df['created_at']
# af = clean_df['Customer Since'] == clean_df['M-Y']
# ac = pd.Series(ac)
# ac
# ac.nunique()

KeyError: 'M-Y'

In [12]:
ab.columns

Index(['index', 'item_id', 'status', 'created_at', 'sku', 'price',
       'qty_ordered', 'grand_total', 'increment_id', 'category_name_1',
       'discount_amount', 'payment_method', 'Working Date', 'BI Status',
       ' MV ', 'Year', 'Month', 'Customer Since', 'M-Y', 'FY', 'Customer ID'],
      dtype='object')

Database Tables

Customers
- customer_id
- customer_since

Products
- 
- sku
- category_name_1

Orders
- item_id
- status
- created_at
- price
- qty_ordered
- payment method
- Month

sales
- grand_total
- BI Status
- MV
- discount_amount
- FY

In [23]:
ab.tail(5)

,index,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,discount_amount,payment_method,BI Status,MV,Year,Month,Customer Since,FY,Customer ID
576475,584519,905204,cod,8/28/2018,WOFSCE5AE00357AECDE,699.0,1,849.0,100562385,Women's Fashion,0.0,cod,Valid,699,2018,8,2018-8,FY19,115320.0
576476,584520,905205,processing,8/28/2018,MATHUA5AF70A7D1E50A,35599.0,1,35899.0,100562386,Mobiles & Tablets,0.0,bankalfalah,Gross,"35,599",2018,8,2018-8,FY19,115326.0
576477,584521,905206,processing,8/28/2018,MATSAM5B6D7208C6D30,129999.0,2,652178.0,100562387,Mobiles & Tablets,0.0,bankalfalah,Gross,"259,998",2018,8,2018-7,FY19,113474.0
576478,584522,905207,processing,8/28/2018,MATSAM5B1509B4696EA,87300.0,2,652178.0,100562387,Mobiles & Tablets,0.0,bankalfalah,Gross,"174,600",2018,8,2018-7,FY19,113474.0
576479,584523,905208,processing,8/28/2018,MATSAM5B10F91A9B6AB,108640.0,2,652178.0,100562387,Mobiles & Tablets,0.0,bankalfalah,Gross,"217,280",2018,8,2018-7,FY19,113474.0

In [79]:
584523-576481

8042

In [ ]:
den = df_pl.drop_nulls()
# den.describe()

dan = df_pd.dropna()
# dan.describe()
# Nulls dropped

dan.info()
df_pd # NAs present

### Checking Partionable Columns with Null Values Removed

In [ ]:
dict_list = []
for col in df_pd.columns:
    ab = df_pd[col].nunique()
    dict_list.append(ab)

for i in dict_list:
    print(i)

584524
16
789
84889
9121
74
36829
408785
16
7224
28058
18
789
4
9720
3
12
26
26
3
115326

### Checking Partionable Columns with Null Values Present

In [22]:
dict_list = []
for col in df_pd.columns:
    ab = df_pd[col].value_counts()
    dict_list.append(ab)

for i in dict_list:
    print(i)

# Null values present

item_id
905208    1
211131    1
211133    1
211134    1
211135    1
         ..
211149    1
211147    1
211146    1
211145    1
211144    1
Name: count, Length: 584524, dtype: int64
status
complete          233685
canceled          201249
received           77290
order_refunded     59529
refund              8050
cod                 2859
paid                1159
closed               494
payment_review        57
pending               48
processing            33
holded                31
fraud                 10
pending_paypal         7
\N                     4
exchange               4
Name: count, dtype: int64
created_at
11/25/2016    15169
11/17/2017    13698
11/24/2017    13191
5/19/2017     11511
11/23/2016     8478
              ...
8/22/2018        92
9/14/2016        83
07/06/2016       72
9/13/2016        52
07/07/2016       51
Name: count, Length: 789, dtype: int64
sku
MATSAM59DB75ADB2F80              3775
Al Muhafiz Sohan Halwa Almond    2258
emart_00-7                       2027
kcc_krone deal                   1894
infinix_Zero 4-Grey              1793
                                 ...
Mochika_M0001112-12                 1
Mochika_M0001112-8                  1
MEFMAR5A3A0F26690EC                 1
MATBIZ5A702BE6E90AB                 1
MATMY5A4A253C8A5C2                  1
Name: count, Length: 84889, dtype: int64
price
1000.0     11077
999.0      10120
500.0       9215
699.0       8407
499.0       7693
           ...
30399.0        1
1805.0         1
24579.0        1
765.4          1
22950.0        1
Name: count, Length: 9121, dtype: int64
qty_ordered
1      505214
2       46656
3       15406
5       11213
4        4141
        ...
96          1
70          1
185         1
380         1
75          1
Name: count, Length: 74, dtype: int64
grand_total
0.00         9632
1000.00      5146
2000.00      3781
2500.00      3235
5000.00      2912
             ...
4156.60         1
145360.00       1
3813.75         1
28599.00        1
27280.00        1
Name: count, Length: 36829, dtype: int64
increment_id
100266667    72
100286851    47
100346364    45
100476608    43
100535753    41
             ..
100562365     1
100562367     1
100562368     1
100562369     1
100562370     1
Name: count, Length: 408785, dtype: int64
category_name_1
Mobiles & Tablets     115710
Men's Fashion          92221
Women's Fashion        59721
Appliances             52413
Superstore             43613
Beauty & Grooming      41496
Soghaat                34011
Others                 29218
Home & Living          26504
Entertainment          26326
Health & Sports        17502
Kids & Baby            16494
Computing              15933
\N                      7850
School & Education      3478
Books                   1870
Name: count, dtype: int64
sales_commission_code
\N              339001
40968             2710
C-LHW-50074       2434
C-RWP-31924       1720
cisb30211         1613
                 ...
14agust              1
C KHIW 40537         1
R_LHW-104419         1
R-LHW-10441          1
C-43409-SGD          1
Name: count, Length: 7224, dtype: int64
discount_amount
0.000       376306
1000.000      5426
2000.000      4143
500.000       3648
200.000       3496
             ...
269.925          1
94.740           1
242.860          1
262.900          1
402.385          1
Name: count, Length: 28058, dtype: int64
payment_method
cod                  271960
Payaxis               97641
Easypay               82900
jazzwallet            35145
easypay_voucher       31176
bankalfalah           23065
jazzvoucher           15633
Easypay_MA            14028
customercredit         7555
apg                    1758
ublcreditcard           882
cashatdoorstep          732
mcblite                 723
mygateway               669
internetbanking         472
productcredit           125
marketingexpense         45
financesettlement        15
Name: count, dtype: int64
Working Date
11/25/2016    15169
11/17/2017    13698
11/24/2017    13191
5/19/2017     11511
11/23/2016     8478
              ...
8/22/2018        92
9/14/2016        83
07/06/2016       72
9/13/2016        52
07/07/2016       51
Name: count, Length: 789, dtype: int64
BI Status
Net      234178
Gross    201454
Valid    148891
#REF!         1
Name: count, dtype: int64
 MV
999       9516
699       7801
499       7157
1,000     6895
399       6506
          ...
4,229        1
4,477        1
6,820        1
20,737       1
9,504        1
Name: count, Length: 9720, dtype: int64
Year
2017    290920
2018    159695
2016    133909
Name: count, dtype: int64
Month
11    155456
5      62603
3      61489
8      48514
7      39151
2      38777
6      34530
4      34091
10     30623
12     29199
1      26067
9      24024
Name: count, dtype: int64
Customer Since
2016-11    82714
2017-11    70785
2016-7     57069
2016-9     46746
2017-5     35356
2018-3     32052
2018-2     23989
2016-8     21051
2017-8     19088
2017-3     18234
2016-10    17546
2017-4     16826
2018-5     16076
2017-6     15593
2017-10    14618
2017-7     14035
2017-1     12260
2016-12    10638
2017-2     10293
2018-1      9665
2017-12     8667
2018-4      7626
2017-9      7442
2018-6      6798
2018-7      5330
2018-8      4016
Name: count, dtype: int64
M-Y
Nov-17    83928
Nov-16    71528
Mar-18    41955
May-17    34736
May-18    27867
Feb-18    26916
Aug-17    25083
Apr-17    21678
Jun-17    19793
Mar-17    19534
Jul-17    19275
Oct-17    17499
Dec-17    15747
Sep-16    15433
Jun-18    14737
Dec-16    13452
Jan-17    13195
Oct-16    13124
Jan-18    12872
Apr-18    12413
Aug-18    11896
Feb-17    11861
Aug-16    11535
Jul-18    11039
Jul-16     8837
Sep-17     8591
Name: count, dtype: int64
FY
FY18    306883
FY17    254706
FY19     22935
Name: count, dtype: int64
Customer ID
85775.0    2524
163.0      2349
35.0       1877
33.0       1397
31025.0    1369
           ...
64932.0       1
64930.0       1
64928.0       1
64925.0       1
64924.0       1
Name: count, Length: 115326, dtype: int64

In [ ]:
for col in df_pd.columns:
    print(df_pd[df_pd[col] == r"NaN"].count())

item_id                  0
status                   0
created_at               0
sku                      0
price                    0
qty_ordered              0
grand_total              0
increment_id             0
category_name_1          0
sales_commission_code    0
discount_amount          0
payment_method           0
Working Date             0
BI Status                0
 MV                      0
Year                     0
Month                    0
Customer Since           0
M-Y                      0
FY                       0
Customer ID              0
dtype: int64
item_id                  0
status                   0
created_at               0
sku                      0
price                    0
qty_ordered              0
grand_total              0
increment_id             0
category_name_1          0
sales_commission_code    0
discount_amount          0
payment_method           0
Working Date             0
BI Status                0
 MV                      0
Year                     0
Month                    0
Customer Since           0
M-Y                      0
FY                       0
Customer ID              0
dtype: int64
item_id                  0
status                   0
created_at               0
sku                      0
price                    0
qty_ordered              0
grand_total              0
increment_id             0
category_name_1          0
sales_commission_code    0
discount_amount          0
payment_method           0
Working Date             0
BI Status                0
 MV                      0
Year                     0
Month                    0
Customer Since           0
M-Y                      0
FY                       0
Customer ID              0
dtype: int64
item_id                  0
status                   0
created_at               0
sku                      0
price                    0
qty_ordered              0
grand_total              0
increment_id             0
category_name_1          0
sales_commission_code    0
discount_amount          0
payment_method           0
Working Date             0
BI Status                0
 MV                      0
Year                     0
Month                    0
Customer Since           0
M-Y                      0
FY                       0
Customer ID              0
dtype: int64
item_id                  0
status                   0
created_at               0
sku                      0
price                    0
qty_ordered              0
grand_total              0
increment_id             0
category_name_1          0
sales_commission_code    0
discount_amount          0
payment_method           0
Working Date             0
BI Status                0
 MV                      0
Year                     0
Month                    0
Customer Since           0
M-Y                      0
FY                       0
Customer ID              0
dtype: int64
item_id                  0
status                   0
created_at               0
sku                      0
price                    0
qty_ordered              0
grand_total              0
increment_id             0
category_name_1          0
sales_commission_code    0
discount_amount          0
payment_method           0
Working Date             0
BI Status                0
 MV                      0
Year                     0
Month                    0
Customer Since           0
M-Y                      0
FY                       0
Customer ID              0
dtype: int64
item_id                  0
status                   0
created_at               0
sku                      0
price                    0
qty_ordered              0
grand_total              0
increment_id             0
category_name_1          0
sales_commission_code    0
discount_amount          0
payment_method           0
Working Date             0
BI Status                0
 MV                      0
Year                     0
Month                    0
Customer Since           0
M-Y                      0
FY                       0
Customer ID              0
dtype: int64
item_id                  0
status                   0
created_at               0
sku                      0
price                    0
qty_ordered              0
grand_total              0
increment_id             0
category_name_1          0
sales_commission_code    0
discount_amount          0
payment_method           0
Working Date             0
BI Status                0
 MV                      0
Year                     0
Month                    0
Customer Since           0
M-Y                      0
FY                       0
Customer ID              0
dtype: int64
item_id                  0
status                   0
created_at               0
sku                      0
price                    0
qty_ordered              0
grand_total              0
increment_id             0
category_name_1          0
sales_commission_code    0
discount_amount          0
payment_method           0
Working Date             0
BI Status                0
 MV                      0
Year                     0
Month                    0
Customer Since           0
M-Y                      0
FY                       0
Customer ID              0
dtype: int64
item_id                  0
status                   0
created_at               0
sku                      0
price                    0
qty_ordered              0
grand_total              0
increment_id             0
category_name_1          0
sales_commission_code    0
discount_amount          0
payment_method           0
Working Date             0
BI Status                0
 MV                      0
Year                     0
Month                    0
Customer Since           0
M-Y                      0
FY                       0
Customer ID              0
dtype: int64
item_id                  0
status                   0
created_at               0
sku                      0
price                    0
qty_ordered              0
grand_total              0
increment_id             0
category_name_1          0
sales_commission_code    0
discount_amount          0
payment_method           0
Working Date             0
BI Status                0
 MV                      0
Year                     0
Month                    0
Customer Since           0
M-Y                      0
FY                       0
Customer ID              0
dtype: int64
item_id                  0
status                   0
created_at               0
sku                      0
price                    0
qty_ordered              0
grand_total              0
increment_id             0
category_name_1          0
sales_commission_code    0
discount_amount          0
payment_method           0
Working Date             0
BI Status                0
 MV                      0
Year                     0
Month                    0
Customer Since           0
M-Y                      0
FY                       0
Customer ID              0
dtype: int64
item_id                  0
status                   0
created_at               0
sku                      0
price                    0
qty_ordered              0
grand_total              0
increment_id             0
category_name_1          0
sales_commission_code    0
discount_amount          0
payment_method           0
Working Date             0
BI Status                0
 MV                      0
Year                     0
Month                    0
Customer Since           0
M-Y                      0
FY                       0
Customer ID              0
dtype: int64
item_id                  0
status                   0
created_at               0
sku                      0
price                    0
qty_ordered              0
grand_total              0
increment_id             0
category_name_1          0
sales_commission_code    0
discount_amount          0
payment_method           0
Working Date             0
BI Status                0
 MV                      0
Year                     0
Month                    0
Customer Since           0
M-Y                      0
FY                       0
Customer ID              0
dtype: int64
item_id                  0
status                   0
created_at               0
sku                      0
price                    0
qty_ordered              0
grand_total              0
increment_id             0
category_name_1          0
sales_commission_code    0
discount_amount          0
payment_method           0
Working Date             0
BI Status                0
 MV                      0
Year                     0
Month                    0
Customer Since           0
M-Y                      0
FY                       0
Customer ID              0
dtype: int64
item_id                  0
status                   0
created_at               0
sku                      0
price                    0
qty_ordered              0
grand_total              0
increment_id             0
category_name_1          0
sales_commission_code    0
discount_amount          0
payment_method           0
Working Date             0
BI Status                0
 MV                      0
Year                     0
Month                    0
Customer Since           0
M-Y                      0
FY                       0
Customer ID              0
dtype: int64
item_id                  0
status                   0
created_at               0
sku                      0
price                    0
qty_ordered              0
grand_total              0
increment_id             0
category_name_1          0
sales_commission_code    0
discount_amount          0
payment_method           0
Working Date             0
BI Status                0
 MV                      0
Year                     0
Month                    0
Customer Since           0
M-Y                      0
FY                       0
Customer ID              0
dtype: int64
item_id                  0
status                   0
created_at               0
sku                      0
price                    0
qty_ordered              0
grand_total              0
increment_id             0
category_name_1          0
sales_commission_code    0
discount_amount          0
payment_method           0
Working Date             0
BI Status                0
 MV                      0
Year                     0
Month                    0
Customer Since           0
M-Y                      0
FY                       0
Customer ID              0
dtype: int64
item_id                  0
status                   0
created_at               0
sku                      0
price                    0
qty_ordered              0
grand_total              0
increment_id             0
category_name_1          0
sales_commission_code    0
discount_amount          0
payment_method           0
Working Date             0
BI Status                0
 MV                      0
Year                     0
Month                    0
Customer Since           0
M-Y                      0
FY                       0
Customer ID              0
dtype: int64
item_id                  0
status                   0
created_at               0
sku                      0
price                    0
qty_ordered              0
grand_total              0
increment_id             0
category_name_1          0
sales_commission_code    0
discount_amount          0
payment_method           0
Working Date             0
BI Status                0
 MV                      0
Year                     0
Month                    0
Customer Since           0
M-Y                      0
FY                       0
Customer ID              0
dtype: int64
item_id                  0
status                   0
created_at               0
sku                      0
price                    0
qty_ordered              0
grand_total              0
increment_id             0
category_name_1          0
sales_commission_code    0
discount_amount          0
payment_method           0
Working Date             0
BI Status                0
 MV                      0
Year                     0
Month                    0
Customer Since           0
M-Y                      0
FY                       0
Customer ID              0
dtype: int64

In [45]:
df_pd['sales_commission_code'].replace(r"\N", 'Unknown')

0             Unknown
1             Unknown
2             Unknown
3         R-FSD-52352
4             Unknown
             ...
584519            NaN
584520            NaN
584521            NaN
584522            NaN
584523            NaN
Name: sales_commission_code, Length: 584524, dtype: object

0                  \N
1                  \N
2                  \N
3         R-FSD-52352
4                  \N
             ...
584519            NaN
584520            NaN
584521            NaN
584522            NaN
584523            NaN
Name: sales_commission_code, Length: 584524, dtype: object